version: "3.2"

services:
  cassandra1:
    image: cassandra-db:4.1-126
    container_name: 1.prod.photo-features-cdb.dc
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=1.prod.photo-features-cdb.dc,2.prod.photo-features-cdb.dc,3.prod.photo-features-cdb.dc
    networks:
      photo-features-cdb-cluster-network:
        ipv4_address: 172.22.1.1
    volumes:
      - ${DATA_PATH}/volume1:/var/lib/cassandra:rw

  cassandra2:
    image: cassandra-db:4.1-126
    container_name: 2.prod.photo-features-cdb.dc
    environment:
      - CASSANDRA_SEEDS=1.prod.photo-features-cdb.dc,2.prod.photo-features-cdb.dc,3.prod.photo-features-cdb.dc
    networks:
      photo-features-cdb-cluster-network:
        ipv4_address: 172.22.1.2
    volumes:
      - ${DATA_PATH}/volume2:/var/lib/cassandra:rw

  cassandra3:
    image: cassandra-db:4.1-126
    container_name: 3.prod.photo-features-cdb.dc
    environment:
      - CASSANDRA_SEEDS=1.prod.photo-features-cdb.dc,2.prod.photo-features-cdb.dc,3.prod.photo-features-cdb.dc
    networks:
      photo-features-cdb-cluster-network:
        ipv4_address: 172.22.1.3
    volumes:
      - ${DATA_PATH}/volume3:/var/lib/cassandra:rw

networks:
  photo-features-cdb-cluster-network:
    name: photo-features-cdb-cluster-network
    external: true
